/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import database.DBbean;
import java.sql.Connection;
import java.util.ArrayList;

import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Paragraph;

import com.itextpdf.text.Font;
import com.itextpdf.text.Document;
import java.io.FileOutputStream;

/**
 *
 * @author Eli
 */
public class DoctorListOfSpecalists {

    private Connection conn;

    private ArrayList<String> patientData;
    private ArrayList<String> specalistData;
//    private ArrayList<String> refferalData;

    private String refillsHTML;
    private String referalsHTML;

    private String letterCreated;

    public DoctorListOfSpecalists(Connection conn) {
        this.conn = conn;

    }

    public void dbSelect() {
        DBbean dao = new DBbean();

        dao.getConnection(conn);

        patientData = dao.selectAllPatientNameID();
        specalistData = dao.selectAllSpecalists();
//        refferalData = dao.selectAllReferal();

    }

    public void createHTML() {
//        Creating drop downs to create a referal
        refillsHTML = "<label>Choose a patient: </label>";
        refillsHTML = refillsHTML + "<select name='patient' id = 'patient'>";

        for (int i = 0; i < patientData.size(); i += 2) {
            refillsHTML = refillsHTML + "<option value='" + patientData.get(i + 1) + "'>" + "ID: " + patientData.get(i) + " Name: " + patientData.get(i + 1) + "</option> ";
        }

        refillsHTML = refillsHTML + "</select>";

        refillsHTML = refillsHTML + "<br><label>Choose a specalist:</label>";
        refillsHTML = refillsHTML + "<select name='specalist' id = 'specalist'>";

        for (int i = 0; i < specalistData.size(); i += 3) {
            refillsHTML = refillsHTML + "<option value='" + specalistData.get(i) + "'>" + "Specalist: " + specalistData.get(i) + " Specalism: " + specalistData.get(i + 1) + "</option> ";
        }
        refillsHTML = refillsHTML + "</select><br>";

        refillsHTML = refillsHTML + "<input type='submit'  value = 'Create Referal'>";


    }

    public String createPDF(String directory, String patient, String specalist, String doctor) {
//        using iText pdf to write to write to folder
        DBbean dao = new DBbean();

        dao.getConnection(conn);

        String specalism = "";
        String email = "";
        for (int i = 0; i < specalistData.size(); i += 3) {
            if (specalist.equals(specalistData.get(i))) {
                specalism = specalistData.get(i + 1);
                email = specalistData.get(i + 2);
            }
        }
        String file = (directory + "SpecalistLetter-"+ patient + specalist).replaceAll(" ", "") + ".pdf";
        System.out.println("file"+file);
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(file));
            document.open();

            Font bigFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
                    Font.BOLD);

            Font smallFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
                    Font.NORMAL);
            Paragraph page = new Paragraph();

            // Will create: Report generated by: _name, _date
            page.add(
                    new Paragraph(
                            "SmartCare GP Sugery,",
                            smallFont));
            page.add(
                    new Paragraph(
                            "Smart Company Road,",
                            smallFont));
            page.add(
                    new Paragraph(
                            "BS1 111,",
                            smallFont));

            page.add(
                    new Paragraph(
                            "Bristol",
                            smallFont));
            page.add(
                    new Paragraph(
                            "United Kingdom,",
                            smallFont));

            // We add one empty line
            page.add(
                    new Paragraph(" "));
            // Lets write a big header
            page.add(
                    new Paragraph("Referal Leffter for " + patient, bigFont));

            page.add(
                    new Paragraph(" "));

            page.add(
                    new Paragraph(
                            "Dear " + specalist,
                            smallFont));

            page.add(
                    new Paragraph(" "));

            page.add(
                    new Paragraph(
                            "After a recent appointment with " + patient + " I felt best I refer them to you for a specalist " + specalism + " appointment.",
                            smallFont));

            page.add(
                    new Paragraph(" "));

            page.add(
                    new Paragraph(
                            "Kind Regards",
                            smallFont));
            page.add(
                    new Paragraph(
                            "Dr " + doctor,
                            smallFont));

            document.add(page);
            document.close();

        } catch (Exception e) {

            e.printStackTrace();

        }

        letterCreated = "SpecalistLetter-"+(patient + specalist).replaceAll(" ", "") + ".pdf";
        System.out.println("letterCreated"+ letterCreated);

        boolean sucsses = dao.insertRefferal(email, doctor, patient, letterCreated, specalism);

        if (sucsses) {
            return "<p>Referal Letter for paitnet " + patient + " created for " + specalism + " to see "+specalist + " .Please email to " + email +"</p>";
        } else {
            return "<p>Referal Letter for paitnet " + patient + " already exists " + specalism + " to see "+specalist + " .Please email to " + email +"</p>";
           
        }

    }

    public String getReferalsHTML() {
        return referalsHTML;
    }

    public String getRefillsHTML() {
        return refillsHTML;
    }

    public String getLetterCreated() {
        return letterCreated;
    }

    
    
}
